# This is a basic workflow to help you get started with Actions

name: approval

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  request-approval:
    runs-on: windows-latest
    steps:
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true         
    - name: Connect to Logic App
      id: GetUrl
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $url = (Get-AzLogicAppTriggerCallbackUrl -ResourceGroupName openhackn82382w0rg -Name ApprovalDemo -TriggerName manual).Value
          if ($url)
          {
          echo "::add-mask::$url"
          echo "::set-output name=LogicAppUrl::$url"
          }          
        azPSVersion: '3.1.0'          
    - name: Request for approval
      uses: bcstestit/invoke-Azure-Logic-App@v3
      with:          
        url: ${{ steps.GetUrl.outputs.LogicAppUrl }}
        approvers: ${{ secrets.APPROVERS }}
        instructions: "Verify the test results and functionality on a dummy environment"
        repo-token: ${{ secrets.REPOTOKEN }}
